# Generated by Django 4.0.6 on 2022-07-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_booking_alter_room_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
