# Generated by Django 4.0.6 on 2022-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
