# Generated by Django 4.0.6 on 2022-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_booking_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('contact', models.CharField(max_length=40, null=True)),
                ('feedback', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
